# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20160921_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the box', max_length=1000),
        ),
    ]
