# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20160921_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ['max_length']},
        ),
        migrations.AlterField(
            model_name='boxinstance',
            name='box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Book'),
        ),
        migrations.AlterField(
            model_name='boxinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
       
    ]
